name: Build and Run Docker Compose

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:

  build-images:
    runs-on: self-hosted
    strategy:
      matrix:
        image_name: [ "cvat-server", "cvat-ui", "cvat-opa" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check docker version
        run: docker version

      - name: Build Docker image ${{ matrix.image_name }}
        uses: ./.github/actions/build-image-stage
        with:
          image_name: ${{ matrix.image_name }}

  deploy:
    runs-on: self-hosted
    needs: build-images     # â¬… ensures all images are built first
    steps:
      - name: Show built images
        run: docker images

      - name: Run docker compose
        run: docker compose -f docker-compose-self-build.yml up -d

      - name: Show running containers
        run: docker ps -a
