name: Build and Run Docker Compose

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:



jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check docker version
        run: docker version

      - uses: ./.github/actions/build-image
        with:
          image_name: cvat-server
          dockerfile: Dockerfile.server

      - uses: ./.github/actions/build-image
        with:
          image_name: cvat-ui
          dockerfile: Dockerfile.ui

      - uses: ./.github/actions/build-image
        with:
          image_name: redis-inme
          dockerfile: Dockerfile.redis-inmem

      - uses: ./.github/actions/build-image
        with:
          image_name: redis-ondisk
          dockerfile: Dockerfile.redis-ondisk
		  
	  - uses: ./.github/actions/build-image
        with:
          image_name: postgres
          dockerfile: Dockerfile.postgres
		  
	  - uses: ./.github/actions/build-image
        with:
          image_name: clickhouse
          dockerfile: Dockerfile.clickhouse
	  - uses: ./.github/actions/build-image
        with:
          image_name: opa
          dockerfile: Dockerfile.opa

      - uses: ./.github/actions/build-image
        with:
          image_name: vector
          dockerfile: Dockerfile.vector
		  
	  - uses: ./.github/actions/build-image
        with:
          image_name: grafana
          dockerfile: Dockerfile.grafana
		  
	  - uses: ./.github/actions/build-image
        with:
          image_name: traefik
          dockerfile: Dockerfile.traefik
      

      - name: Show built images
        run: docker images

      - name: Run docker compose
        run: |
          docker compose -f docker-compose-self-build.yml up -d

      - name: Show running containers
        run: docker ps -a
