name: Build and Run Docker Compose

# on:
#   push:
#     branches: main
#   pull_request:
#     branches: main
#   workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check docker version
        run: docker version

      - name: Build Docker image cvat-server
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-server
          dockerfile: Dockerfile.server

      - name: Build Docker image cvat-ui
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-ui
          dockerfile: Dockerfile.ui

      - name: Build Docker image cvat-redis-inmem
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-redis-inmem
          dockerfile: Dockerfile.redis-inmem

      - name: Build Docker image cvat-redis-ondisk
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-redis-ondisk
          dockerfile: Dockerfile.redis-ondisk

      - name: Build Docker image cvat-postgres
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-postgres
          dockerfile: Dockerfile.postgres

      - name: Build Docker image cvat-clickhouse
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-clickhouse
          dockerfile: Dockerfile.clickhouse

      - name: Build Docker image cvat-opa
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-opa
          dockerfile: Dockerfile.opa

      - name: Build Docker image cvat-vector
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-vector
          dockerfile: Dockerfile.vector

      - name: Build Docker image cvat-grafana
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-grafana
          dockerfile: Dockerfile.grafana

      - name: Build Docker image cvat-traefik
        uses: ./.github/actions/build-image
        with:
          image_name: cvat-traefik
          dockerfile: Dockerfile.traefik

      - name: Show built images
        run: docker images

      - name: Run docker compose
        run: |
          docker compose -f docker-compose-self-build.yml up -d

      - name: Show running containers
        run: docker ps -a
