name: Build and Run Docker Compose

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check docker version
        run: docker version

      - name: Building Containers
        run: |

          docker build . --target cvat-server -t cvat-server:latest
          docker build . --target cvat-ui -t cvat-ui:latest
          docker build . --target cvat-redis-inmem -t cvat-redis-inmem:latest
          docker build . --target cvat-redis-ondisk -t cvat-redis-ondisk:latest
          docker build . --target cvat-postgres -t cvat-postgres:latest
          docker build . --target cvat-clickhouse -t cvat-clickhouse:latest
          docker build . --target cvat-opa -t cvat-opa:latest
          docker build . --target cvat-grafana -t cvat-grafana:latest
          docker build . --target cvat-traefik -t cvat-traefik:latest
          

      - name: Show built images
        run: docker images

      - name: Run docker compose
        run: |
          docker compose -f docker-compose-self-build.yml up -d

      - name: Show running containers
        run: docker ps -a
